### ISSUE TITLE
Описать Git flow для репозиториев с ручными и программными заданиями

### ISSUE THREAD

**Issue by MikhailovAlexander** [HSE-algo-23-crow/docs#3]
Подготовить описание Git flow для репозиториев с ручными и программными задачами - какие ветви используются для заданий, как создаютя ветви для решений и куда они вливаются.

Для иллюстраций использовать Mermaid диаграммы
[Gitgraph Diagrams](https://mermaid.js.org/syntax/gitgraph.html)

**Comment by ImRedTea** [comment]
команда YES заявляется на выполнение
